spring.application.name=mso-ventas-liverpool
spring.application.title=adad



# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/api-docs
