
# MongoDB Produccion empresa
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Servidor
server.port=${PORT:8080}

# Logs
 logging.level.org.springframework.data.mongodb=WARN